name: main
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 

  cupertino_icons: ^1.0.2

  # MICROFRONTENDS
  dependencies:
    path: ../dependencies

  design_system:
    path: ../design_system

  shared:
    path: ../shared

  feed:
    path: ../feed

  profile:
    path: ../profile

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_flavorizr: ^2.1.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

# flutter pub run flutter_flavorizr
flavorizr:
  ide: vscode
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Posterr dev"
      android:
        applicationId: "com.posterr.dev"
      ios:
        bundleId: "com.posterr.dev"
    hml:
      app:
        name: "Posterr hml"
      android:
        applicationId: "com.posterr.hml"
      ios:
        bundleId: "com.posterr.hml"
    prod:
      app:
        name: "Posterr prod"
      android:
        applicationId: "com.posterr.prod"
      ios:
        bundleId: "com.posterr.prod"