name: auth

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # MICROFRONTENDS
  dependencies:
    path: ../dependencies

  shared:
    path: ../shared

dev_dependencies:
  flutter_lints: ^2.0.1
  