name: dependencies

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.0.0-dev.9
  equatable: ^2.0.3
  dartz: ^0.10.1
  firebase_core: ^1.19.1
  firebase_analytics: ^9.1.12
  firebase_crashlytics: ^2.8.4

dev_dependencies:
  flutter_lints: ^2.0.1