name: dependencies

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.0.0-dev.9
  equatable: ^2.0.3
  dartz: ^0.10.1  

dev_dependencies:
  flutter_lints: ^2.0.1