name: design_system

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # MICROFRONTENDS
  dependencies:
    path: ../dependencies

dev_dependencies:
  faker: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  